### PR TITLE
Fix identy_switch and support array for smtp_host

### PR DESCRIPTION
**Pull request by HLFH**
Check the commits ;)

### CODE REVIEW

**Review by toteph42 — APPROVED** [review]
Accepted

**Review by toteph42 — APPROVED** [review]
Accepted

**Review by toteph42 — APPROVED** [review]

**Comment by toteph42** [comment]
Something went wrong

**Comment by HLFH** [comment]
What went wrong?

**Comment by toteph42** [comment]
I Sorry, I'm not very  familiar with pull requests. I was not able to deny some of your suggested fixes. I added some of your suggestions to code in 1.0.13.

**Pull request closed without merging**
